### ISSUE TITLE
Regenerate source-code with new generator template

### ISSUE THREAD

**Issue by PutraSudaryanto** [ommu/gii-template#2]
#### TASK
- [ ] setting
- [x] profile
- [x] profile category
- [x] document type
- [x] profile document
- [ ] members
- [x] userlevel
- [ ] member users
- [x] company type
- [ ] member company
- [x] member contact category
- [ ] member company contact
- [x] member history displayname
- [x] member history username
- [ ] member recruiter
- [ ] member documents
- [ ] member categories
- [ ] member views
- [ ] member view history
- [x] friend type
- [ ] friends
- [ ] friend history
- [ ] followers
- [ ] follower history

**Comment by PutraSudaryanto** [comment]
wrong repository
